#!/usr/bin/env bash
#=================================================================
#Nome do script: script
#Descrição           : script para facilitar a criação de scripts
#Autor               : weverton
#Data                : 04-11-24
#Versão              : 0.1
#=================================================================
#Parâmetros          : script < nome > 
# -opcao             : sem argumento lista todos os scripts criados.
#  argumento         : < nome do script > que está sendo criado ou que existe
#=================================================================
#=================================================================

DIR="/usr/local/bin/"
EDITOR="nano"
DATA=$(date +%d-%m-%y)


[[ $# -ne 1 ]] && ls $DIR && exit 0

if [[ -f $DIR$1 ]]; then

read -p " Script já existe deseja abrir s/n? " OPT

[[ $OPT == "s" ]] && $EDITOR $DIR$1 && exit 0 || exit 0

fi 

echo "#!/usr/bin/env bash
#=================================================================
#Nome do script: script
#Descrição           : Breve descrição do que o script faz.
#Autor               : $USER
#Data                : $DATA
#Versão              : 0.1
#=================================================================
#Parâmetros          :
# -opcao             : descrição da opção
#  argumento         : descrição do argumento
#=================================================================
#================================================================= 
" > $DIR$1

chmod 711 $DIR$1
$EDITOR $DIR$1
